# -*- coding: utf-8 -*-
"""ccalculadora_reajuste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrqS5AivS3EyX3y1tR42T0nzbGal4GTO
"""

while True:
  nome = input('Qual seu nome? ')
  sal = float(input("Quanto é seu salário?"))
  if sal <= 5000:
    res1 = sal * 1.10
    print(f'Prazer {nome}! Seu salário terá um aumento de 10%: {res1:.2f}')
  else:
    res2 = sal * 1.20
    print(f'Prazer {nome}! Seu salário terá um aumento de 20%: {res2:.2f}')
  resposta = input('Deseja continuar? (S/N) : ')
  if resposta == 'N':
    break]
  elif resposta == 'n':
    break
  else:
    continue